Repository edoardottt/awesome-hacker-search-engines, pull requests merged in 2024-10, with the labels that each got.

#238 Adding SubdomainRadar.io
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#245 Update README.md
  README.md
Labels: enhancement, hacktoberfest

#248 Added `BreachCheck.io` in `Leaks` Section #244
  README.md
Labels: hacktoberfest-accepted

#253 Feat: Added OCCRP Aleph
  README.md
Labels: hacktoberfest-accepted

#259 Add HaveIBeenSold to Credentials section
  README.md
Labels: enhancement, hacktoberfest-accepted

#261 Add leak.sx
  README.md
Labels: enhancement, hacktoberfest-accepted
